
services:
  - type: web
    name: wake-me-when-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: your-mongo-uri-here
      - key: JWT_SECRET
        value: your-jwt-secret
    rootDir: .

  - type: web
    name: wake-me-when-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: client
