services:
  - type: web
    name: wake-me-when-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://danushriprakashsaranya:ChUyqg6MbrcmTbZZ@cluster1.m6tjv.mongodb.net/wakeme
    rootDir: .

  - type: web
    name: wake-me-when-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: .
